### ISSUE TITLE
Cloning problem

### ISSUE THREAD

**Issue by JulStrat** [benibela/fpc-map-benchmark#1]
Folder **fpc-map-benchmark** is empty after cloning repository  - 
`
$ git clone https://github.com/benibela/fpc-map-benchmark.git
Cloning into 'fpc-map-benchmark'...
remote: Enumerating objects: 1193, done.
remote: Counting objects: 100% (1193/1193), done.
remote: Compressing objects: 100% (605/605), done.
remote: Total 1296 (delta 631), reused 1150 (delta 588), pack-reused 103
Receiving objects: 100% (1296/1296), 927.44 KiB | 1.32 MiB/s, done.
Resolving deltas: 100% (673/673), done.
error: invalid path 'results/results-r44777-O4/libstdc++s_std::unordered_map.200.0.0'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**Comment by benibela** [comment]
Do you use Windows? That probably does not like `:` in the filename

You could checkout everything besides those files. They are the results for one map, so they are not really relevant

**Comment by JulStrat** [comment]
Yes, I am on Windows.
I will try Linux. Thanks.
